version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Installing dependencies..."
      - npm ci --production=false
      - echo "Installing Tailwind CSS globally..."
      - npm install -g tailwindcss@latest
      - echo "Dependencies installed successfully"
      - echo "Node version: $(node --version)"
      - echo "NPM version: $(npm --version)"
  
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Setting up environment..."
      - echo "Current directory: $(pwd)"
      - echo "Directory contents:"
      - ls -la
      - echo "Checking for key files:"
      - test -f package.json && echo "✓ package.json found" || echo "✗ package.json missing"
      - test -f tailwind.config.ts && echo "✓ tailwind.config.ts found" || echo "✗ tailwind.config.ts missing"
      - test -f app/globals.css && echo "✓ globals.css found" || echo "✗ globals.css missing"
  
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Building Tailwind CSS..."
      - npx tailwindcss -i ./app/globals.css -o ./app/output.css --minify
      - echo "✓ Tailwind CSS compiled"
      - echo "Building Next.js application..."
      - npm run build
      - echo "✓ Next.js build completed"
      - echo "Build artifacts:"
      - ls -la .next/
      - echo "Checking build output:"
      - test -d .next && echo "✓ .next directory created" || echo "✗ .next directory missing"
  
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Build completed on $(date)"
      - echo "Final build artifacts:"
      - ls -la .next/
      - echo "Copying build artifacts..."

artifacts:
  files:
    - .next/**/*
    - public/**/*
    - package.json
    - next.config.mjs
    - tailwind.config.ts
    - postcss.config.mjs
    - app/globals.css
    - app/output.css
    - app/layout.tsx
    - app/page.tsx
  discard-paths: no
  base-directory: .

cache:
  paths:
    - node_modules/**/*
    - .next/cache/**/* 