# HTTPS Configuration for Elastic Beanstalk Environment
# This file configures HTTPS for the shine-env environment

OptionSettings:
  # Load Balancer Configuration
  aws:elbv2:listener:443:
    ListenerEnabled: true
    Protocol: HTTPS
    SSLCertificateArns: arn:aws:acm:us-east-1:396608803476:certificate/d22adc54-b99d-4be1-95ae-df3ea291da6b
  
  # Security Group Configuration
  aws:autoscaling:launchconfiguration:
    SecurityGroups: sg-xxxxxxxxx
  
  # Environment Configuration
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application
    ServiceRole: aws-elasticbeanstalk-service-role
  
  # Application Load Balancer Configuration
  aws:elasticbeanstalk:environment:process:default:
    HealthCheckPath: /health
    Port: 80
    Protocol: HTTP
  
  # HTTPS Redirect Configuration
  aws:elasticbeanstalk:environment:proxy:
    ProxyServer: nginx
  
  # SSL Configuration
  aws:elasticbeanstalk:environment:proxy:staticfiles:
    /static: static/
    /images: images/
  
  # HTTPS Headers
  aws:elasticbeanstalk:environment:proxy:headers:
    X-Forwarded-Proto: https
    X-Forwarded-For: $proxy_add_x_forwarded_for
    X-Real-IP: $remote_addr

# Certificate Details:
# - Certificate ARN: arn:aws:acm:us-east-1:396608803476:certificate/d22adc54-b99d-4be1-95ae-df3ea291da6b
# - Status: ISSUED
# - Domain: *.eba-azwgu4dc.us-east-1.elasticbeanstalk.com
# - Validation: DNS validation completed

# Quick Setup Instructions:
# 1. Certificate is already created and validated
# 2. Update the SSLCertificateArns in this file (DONE)
# 3. Apply configuration: aws elasticbeanstalk update-environment --environment-name shine-env --option-settings file://enable-https-config.yml 