name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      working-directory: ./backend
      run: |
        # Add your test commands here
        python -m pytest tests/ || echo "No tests found"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Create deployment package
      working-directory: ./backend
      run: |
        zip -r ../deploy.zip . -x "*.git*" "*__pycache__*" "*.pyc" "tests/*" "venv/*"
        
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: shine-skincare-backend
        environment_name: shine-skincare-backend-prod
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip
        
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully"
        echo "Backend URL: ${{ secrets.BACKEND_URL }}"

