# Shine Skincare App - New Architecture Docker Compose
# Local development and testing environment

version: '3.8'

services:
  # API Gateway Service
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: shine-api-gateway
    ports:
      - "8080:8080"
    environment:
      - ML_SERVICE_URL=http://ml-service:5000
      - FLASK_ENV=development
    depends_on:
      - ml-service
    networks:
      - shine-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ML Model Service
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: shine-ml-service
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=/app/models/fixed_model_best.h5
      - FLASK_ENV=development
    volumes:
      # Mount the model file for development
      - ../../models/fixed_model_best.h5:/app/models/fixed_model_best.h5:ro
    networks:
      - shine-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: shine-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - ml-service
    networks:
      - shine-network
    restart: unless-stopped

networks:
  shine-network:
    driver: bridge

volumes:
  model-data:
    driver: local
